<?php
     return [
         "Home",
         "Contact With team",
         "Your Name",
         "Phone Number",
         "Email Address",
         "Invest type",
         "Write your comments",
         "Select to subscribe to our newsletter and update and we will send you all updates about.",
         "Submit Now",
         "Email",
         "Call Us",
         "Farm Cycle",
         "Initial Investment",
         "Starting from",
         "username or email",
         "Username or Email",
         "Remember me",
         "Forget Password",
         "Log In",
         "OR",
         "Don’t have an account",
         "Sign Up",
         "Return Period",
         "No data found",
         "Rol",
         "Return",
         "Project Duration",
         "Number Of Return",
         "Invest Amount",
         "About This Farm Project",
         "Create an account and start growing your Money",
         "Create an account",
         "Details",
         "Share This Articles",
         "Categories",
         "Recent post",
         "No data Fond",
         "Unite Price",
         "Invest Now",
         "Available Unit",
         "You are Sponsoring:",
         "Useful Link",
         "Resources",
         "Subscribe",
         "Call Us",
         "Email",
         "Edit Profile",
         "Create Ticket",
         "Enter Subject",
         "Subject",
         "Message",
         "Enter Message",
         "Main Balance",
         "Select Payment",
         "Make Payment",
         "Payment Summery",
         "Select Currency",
         "Log In",
         "Sign Up",
         "Dashboard",
         "Verify Your OTP",
         "Verify Your OTP to Disable",
         "Enter Google Authenticator Code",
         "Enter Your Password",
         "Close",
         "Save changes",
         "Re-generate Confirmation",
         "Create ticket",
         "Support Ticket",
         "Subject",
         "Status",
         "Last Reply",
         "Action",
         "Open",
         "Answered",
         "Replied",
         "Closed",
         "Ticket Conversation",
         "View Ticket",
         "Close Ticket",
         "Are you sure you want to close this ticket",
         "Select Currency",
         "Enter Amount",
         "Make Payment",
         "Payout Summery",
         "Total Invest",
         "Total Profit",
         "Plan Invest",
         "Project Invest",
         "Plan Profit",
         "Project Profit",
         "Last Withdraw",
         "Total Withdraw",
         "Total Deposit",
         "Transaction ID",
         "Amount",
         "Status",
         "Created time",
         "Method",
         "Profile information",
         "Password setting",
         "View Profile",
         "KYC Verification",
         "Switch to Home Page",
         "Verification Center",
         "Submitted At",
         "Type",
         "SL",
         "Invest",
         "Payout",
         'Deposit',
         "Account Setting",
         "First Name",
         "Last Name",
         "Email",
         "Enter your email",
         "Username",
         "Enter your username",
         "Password",
         'Confirm Password',
         "Already have an account",
         "Don’t have an account",
         'Log In',
         "Create Account",
         "Send Link",
         "Email address",
         "Recover Password",
         "Regain access with your seamless and secure account retrieval process in just a few clicks",
         "Reset Password",
         "Write your message",
         "Invest type",
         "Email Address",
         "Phone Number",
         'Your Name',
         "Select to subscribe to our newsletter and update and we will send you all updates about.",
         "Want to get more commission",
         "Refer your friends and earn more commission",
         "submit",
         "New Password",
         "Current Password",
         'Confirm Password'.
         "Times",
         "First name",
         "last name",
         "username",
         "email address",
         "phone number",
         "Mr. John",
         "Doe",
         "example@gmail.com",
         'preferred language',
         "Select Language",
         "Address",
         "change password",
         "Submit",
         "Selected Currency",
         "Confirmation",
         "Are you want to close ticket",
         "All Rights Reserved",
         "Copyright",
         "Account Settings",
         "Upload New Photo",
         "reset",
         "Allowed JPG or PNG. Max size of 3 MB",
         "Address",
         "Update Password",
         "Current password",
         "Password",
         "Repeat password",
         "Change Password",
         "2 FA Security",
         "Verify",
         "You have no notifications",
         "Clear all",
         "Times",
         "Result",
         "Internal Server Error",
         "The server encountered an internal error misconfiguration and was unable to complete your request. Please contact the server administrator.",
         "Sorry, your session has expired.Please refresh and try again",
         "Session Expired",
         "Method Not Allowed",
         "Method Not",
         "Allowed",
         "Not Found",
         "Oops! Not found",
         "The page you’re looking for doesn’t exist. It might have been moved , removed , renamed or might never existed. If you typed the URL directly, please make sure the spelling is correct.",
         "Access",
         "Forbidden",
         "Back To Home",
         "Unauthorized",
         "Authorization",
         "required",
         "Lifetime Earning",
         "Times",
         "Unlimited",
         "Yes",
         "No",
         "Every",
         "In App",
         "Push",
         "SMS",
         "Notification Permission",
         "Waiting for payment preview",
         "In Base Currency",
         "Payable Amount",
         "Charge",
         "Amount In",
         "Deposit Summary",
         "Deposit History",
         "No data to show",
         "Plan Investment",
         "Plan",
         "Profit",
         "Return Period",
         "Upcoming Payment",
         "Received Amount",
         "Project Investment",
         "Project",
         "No. of Unit",
         "Price",
         "Per Unit",
         "Return Period",
         "Verification History",
         "Pay with",
         "Your Card Information",
         "Enter your card number",
         "'Enter the name on your card",
         "Pay with ",
         "CARD NAME",
         "CARD NUMBER",
         "Valid Card Number",
         "Card Name",
         "EXPIRATION DATE",
         "CVC CODE",
         "CVC",
         "PAY NOW",
         "Please Pay",
         "To Get",
         "Pay Now",
         "PLEASE SEND EXACTLY",
         "SCAN TO SEND",
         "Payment Preview",
         "Pay with Khalti",
         "Please follow the instruction below",
         "You have requested to Payment",
         "Confirm Now",
         "Select Bank Currency",
         "Selected",
         "Select Transfer",
         "Select Bank",
         "Automatic Payout",
         "Payout Method",
         "Request Amount",
         "Percentage",
         "Charge Percentage",
         "Charge Fixed",
         "Charge",
         "Amount In Base Currency",
         "Select Recipient Type",
         "Select Recipient",
         "Email",
         "phone",
         "Paypal Id",
         "Payout History",
         "Wallet Balance",
         "Profit Balance",
         "Waiting for payout preview",
         "Investment Plan",
         "Maturity",
         "Number of return",
         "Capital Back",
         "Profile",
         "Profile Details",
         "Invest",
         "View",
         "KYC Information",
         "Your KYC is Pending",
         "Your KYC is Verified",
         "Projects",
         "Title",
         "Unit Price",
         "ROI",
         "Per Return",
         "Project Duration",
         "Referral",
         "Copy this url and share with others",
         "Referral Bonus",
         "Level",
         "Username",
         "Email",
         "Phone Number",
         "Joined At",
         "Referral Bonus",
         "Bonus From",
         "Amount",
         "Remarks",
         "Date",
         "Ticket",
         "File",
         "Transactions",
         "2 Step Security",
         "Two Factor Authenticator",
         "Re-Generate",
         "Disable Two Factor Authenticator",
         "Enable Two Factor Authenticator",
         "Google Authenticator",
         "DOWNLOAD APP",
         "Verify Your OTP",
         "Enter Google Authenticator Code",
         "Close",
         "Verify",
         "Verify Your OTP to Disable",
         "Enter Your Password",
         "Re-generate Confirmation",
         "Are you want to Re-generate Authenticator",
         "Yes",
         "Do not miss any single important notification! Allow your browser to get instant push notification",
         "Please allow your browser to get instant push notification. Allow it from notification setting.",
         "Profit Statistics",
         "Plan Profit",
         "Invest Statistics",
         "Invest History",
         "Ticket Statistics",
         "Withdraw Statistics",
         "Others",
         "Recent Activity (7 Days)",
         "Support",
         "Withdraw",
         "Deposit & Payout History",
         "Transaction Summary",
         "Please confirm your password before continuing.",
         "Forgot Your Password",
         "Resend code",
         "Didn't get Code? Click to",
         "Login",
         "enter captcha",
         "Verify Your Email Address",
         "A fresh verification link has been sent to your email address.",
         "Before proceeding, please check your email for a verification link.",
         "If you did not receive the email",
         "click here to request another",
         "Payment Summary",
         "Total Unit",
         "Days",
         "Unite Price",
         "Investment Last Date",
         "All right reserved",
         "Sign Up",
         "OR",
         "Number of Return",
         "Project duration",
         "Return Period",
         "Maturity",
         "Profit",
         "Capital Back",
         "Search",
         "Plan invest history",
         "Project Invest history",
         "Transaction",
         "Recent Plan Invest",
         "Allow me",
         "Recent Project Invest",
         "Balance",
         "Enter Amount",
         "Confirm",
         "Total Commission",
         "New Ticket",
         "Drag & Drop files here or click to browse",
         "Upload Photo",
         "Reason",
         "Firstname",
         "Lastname",
         "Username",
         "Email Address",
         "Phone Number",
         "Language",
         "Address",
         "save changes",
         "Sign Out",
         "Select Wallet",
         "Every",
         "Month",
         "Year",
         "Day",
         "Search",
         "Per Unit",
         "Per Return",
         "Pending Ticket",
         "Answered Ticket",
         "Closed Ticket",
         "Total Payout",
         "Last Payout",
         "View all",
         "View All",
         "Hour",
         "Profit Commission"
     ];
